-- =============================================================================
-- OnList Club — Struttura iniziale del database (replica del progetto di
-- sviluppo `ppbxhedbludoqnagzugm`).
--
-- Eseguire UNA SOLA VOLTA su un progetto Supabase VUOTO per ottenere la
-- stessa struttura senza dati.
--
-- Ordine di esecuzione:
--   1. Estensioni
--   2. Tabelle (in ordine topologico di dipendenza FK)
--   3. Foreign Key
--   4. Indici
--   5. Funzioni
--   6. Trigger
--   7. ENABLE RLS
--   8. Policy RLS
--   9. View
--
-- NOTE IMPORTANTI (vedi anche il messaggio di accompagnamento):
--   • Le tabelle `utenti`, `notifiche`, `analytics_events` referenziano
--     `auth.users` (schema di Supabase Auth). Questo schema esiste già su
--     ogni progetto Supabase, quindi le FK funzionano subito.
--   • Le function usano `auth.uid()` (Supabase Auth) e `SECURITY DEFINER`.
--     Su un progetto fresh saranno di proprietà di `postgres`.
--   • La function `get_gestore_by_codice` referenzia una tabella `clubs`
--     che NON esiste (la tabella è `locali`). È un bug del DB sorgente:
--     la function viene ricreata identica per fedeltà, MA da fixare prima
--     che venga usata in produzione. Vedi nota a fondo file.
-- =============================================================================


-- =============================================================================
-- 1. ESTENSIONI
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto      WITH SCHEMA extensions;  -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"   WITH SCHEMA extensions;  -- uuid_generate_v4() (legacy)
CREATE EXTENSION IF NOT EXISTS moddatetime   WITH SCHEMA extensions;  -- trigger updated_at automatico
CREATE EXTENSION IF NOT EXISTS postgis       WITH SCHEMA public;      -- geography per coordinate
CREATE EXTENSION IF NOT EXISTS pg_trgm       WITH SCHEMA public;      -- gin_trgm_ops per ricerca città


-- =============================================================================
-- 2. TABELLE (ordine topologico: le referenziate prima delle referenzianti)
-- =============================================================================

-- ── Anagrafiche geografiche ───────────────────────────────────────────────────

CREATE TABLE public.provincia (
  id_provincia   uuid NOT NULL DEFAULT gen_random_uuid(),
  sigla          varchar NOT NULL,
  nome_provincia text    NOT NULL,
  CONSTRAINT provincia_pkey PRIMARY KEY (id_provincia),
  CONSTRAINT provincia_sigla_key UNIQUE (sigla)
);

CREATE TABLE public.citta (
  id_citta     uuid NOT NULL DEFAULT gen_random_uuid(),
  nome_citta   text NOT NULL,
  id_provincia uuid,
  posizione    geography,
  lat          double precision,
  lng          double precision,
  CONSTRAINT citta_pkey PRIMARY KEY (id_citta)
);

CREATE TABLE public.cap (
  id_cap     uuid NOT NULL DEFAULT gen_random_uuid(),
  cap_valore varchar NOT NULL,
  id_citta   uuid,
  CONSTRAINT cap_pkey PRIMARY KEY (id_cap)
);

CREATE TABLE public.posti_famosi (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  nome       varchar NOT NULL,
  id_citta   uuid,
  lat        double precision NOT NULL,
  lng        double precision NOT NULL,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT posti_famosi_pkey PRIMARY KEY (id)
);

-- ── Paesi (prefissi telefonici) ───────────────────────────────────────────────

CREATE TABLE public.paesi (
  id              uuid    NOT NULL DEFAULT gen_random_uuid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamp   NOT NULL DEFAULT now(),
  iso_code        varchar NOT NULL,
  nome            text    NOT NULL,
  numero_prefisso varchar NOT NULL,
  CONSTRAINT countries_phone_pkey PRIMARY KEY (id),
  CONSTRAINT countries_phone_nome_key UNIQUE (nome)
);
COMMENT ON TABLE public.paesi IS
  'Elenco di paesi da dove estrarre il prefisso per il numero di telefono dell''utente';

-- ── Utenti ────────────────────────────────────────────────────────────────────

-- public.utenti.id estende auth.users.id (one-to-one). Su Supabase vuoto
-- auth.users esiste già — quindi la FK non dà errori.
CREATE TABLE public.utenti (
  id            uuid NOT NULL,
  email         text,
  nome          text,
  cognome       text,
  data_nascita  date,
  maggiorenne   boolean,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  raggio_km     integer DEFAULT 20,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE public.utenti_numeri_telefono (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz,
  id_utente   uuid,
  country_id  uuid,
  telefono    varchar,
  is_primary  boolean,
  is_verified boolean,
  CONSTRAINT user_phones_pkey PRIMARY KEY (id)
);

-- ── Locali e personale ────────────────────────────────────────────────────────

CREATE TABLE public.locali (
  id                 uuid NOT NULL DEFAULT gen_random_uuid(),
  nome               text NOT NULL,
  logo_url           text,
  indirizzo          text,
  telefono           text,
  email              text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  famosita           integer NOT NULL DEFAULT 0,
  generi_musicali    text[]  NOT NULL DEFAULT '{}'::text[],
  foto_url           text,
  prezzo_indicativo  smallint NOT NULL DEFAULT 1,
  link_tripadvisor   text,
  descrizione        text,
  id_citta           uuid,
  posizione          geography,
  lat                double precision,
  lng                double precision,
  CONSTRAINT clubs_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.locali IS 'Locali/discoteche registrati sulla piattaforma';

CREATE TABLE public.gestori (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id    uuid NOT NULL,
  codice     text NOT NULL,
  nome       text,
  ruolo      text NOT NULL DEFAULT 'admin'::text,
  attivo     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  email      text,
  CONSTRAINT gestori_pkey PRIMARY KEY (id),
  CONSTRAINT gestori_codice_key UNIQUE (codice)
);
COMMENT ON TABLE public.gestori IS 'Gestori del locale con accesso al gestionale';

CREATE TABLE public.staff (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id    uuid NOT NULL,
  nome       text NOT NULL,
  ruolo      text,
  telefono   text,
  email      text,
  stato      text NOT NULL DEFAULT 'green'::text,
  attivo     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_stato_check CHECK (stato = ANY (ARRAY['green'::text, 'orange'::text, 'blue'::text]))
);
COMMENT ON TABLE public.staff IS 'Staff del locale (PR, barman, sicurezza, ecc.)';

CREATE TABLE public.ingressi_giornalieri (
  id      uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL,
  data    date NOT NULL,
  count   integer NOT NULL DEFAULT 0,
  CONSTRAINT ingressi_giornalieri_pkey PRIMARY KEY (id),
  CONSTRAINT ingressi_giornalieri_club_id_data_key UNIQUE (club_id, data)
);
COMMENT ON TABLE public.ingressi_giornalieri IS
  'Conteggio ingressi per giorno (per i grafici dashboard)';

-- ── Eventi & prevendite ───────────────────────────────────────────────────────

CREATE TABLE public.eventi (
  id                uuid NOT NULL DEFAULT gen_random_uuid(),
  club_id           uuid NOT NULL,
  nome              text NOT NULL,
  descrizione       text,
  ingressi_previsti integer NOT NULL DEFAULT 0,
  incasso_previsto  numeric NOT NULL DEFAULT 0,
  prezzo_ingresso   numeric,
  locandina_url     text,
  stato             text NOT NULL DEFAULT 'attivo'::text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  generi_musicali   text[] NOT NULL DEFAULT '{}'::text[],
  posti_prenotati   integer NOT NULL DEFAULT 0,
  inizio_evento     timestamptz,
  fine_evento       timestamptz,
  CONSTRAINT eventi_pkey PRIMARY KEY (id),
  CONSTRAINT eventi_stato_check CHECK (
    stato = ANY (ARRAY['attivo'::text, 'bozza'::text, 'archiviato'::text, 'annullato'::text])
  )
);
COMMENT ON TABLE public.eventi IS 'Serate ed eventi del locale';

CREATE TABLE public.prevendite (
  id_prevendita        uuid NOT NULL DEFAULT gen_random_uuid(),
  id_evento            uuid NOT NULL,
  prezzo               numeric NOT NULL,
  tipo                 varchar,
  descrizione          text,
  validita             varchar,
  quantita_disponibile integer NOT NULL DEFAULT 0,
  CONSTRAINT prevendita_pkey PRIMARY KEY (id_prevendita)
);

-- ── Tavoli ────────────────────────────────────────────────────────────────────

CREATE TABLE public.tavoli (
  id_tavolo          uuid NOT NULL DEFAULT gen_random_uuid(),
  nome_tavolo        varchar NOT NULL,
  numero_tavolo      integer,
  numero_persone_max integer,
  prezzo_minimo      numeric,
  id_locale          uuid,
  capacita           integer NOT NULL DEFAULT 4,
  posizione          text,
  CONSTRAINT tavolo_pkey PRIMARY KEY (id_tavolo)
);

CREATE TABLE public.tavoli_eventi (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  id_tavolo  uuid NOT NULL,
  id_evento  uuid NOT NULL,
  stato      text NOT NULL DEFAULT 'disponibile'::text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT tavoli_eventi_pkey PRIMARY KEY (id),
  CONSTRAINT tavoli_eventi_id_tavolo_id_evento_key UNIQUE (id_tavolo, id_evento)
);

-- ── Drink ─────────────────────────────────────────────────────────────────────

CREATE TABLE public.drink (
  id_drink uuid NOT NULL DEFAULT gen_random_uuid(),
  nome     varchar NOT NULL,
  prezzo   numeric NOT NULL,
  CONSTRAINT drink_pkey PRIMARY KEY (id_drink)
);

-- ── Ordini & prenotazioni ─────────────────────────────────────────────────────

CREATE TABLE public.ordini (
  id                          uuid NOT NULL DEFAULT gen_random_uuid(),
  utente_id                   uuid NOT NULL,
  importo_totale              numeric NOT NULL,
  valuta                      text NOT NULL DEFAULT 'eur'::text,
  stato                       text NOT NULL DEFAULT 'pending'::text,
  stripe_payment_intent_id    text,
  stripe_checkout_session_id  text,
  stripe_customer_id          text,
  stripe_payment_method_id    text,
  stripe_receipt_url          text,
  stripe_refund_id            text,
  note                        text,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ordini_pkey PRIMARY KEY (id),
  CONSTRAINT ordini_importo_totale_check CHECK (importo_totale >= 0::numeric),
  CONSTRAINT ordini_stato_check CHECK (
    stato = ANY (ARRAY['pending'::text, 'pagato'::text, 'fallito'::text, 'rimborsato'::text, 'annullato'::text])
  )
);

CREATE TABLE public.prenotazioni (
  id              uuid NOT NULL DEFAULT gen_random_uuid(),
  id_evento       uuid NOT NULL,
  id_utente       uuid,
  nome_cliente    text NOT NULL,
  n_persone       integer NOT NULL DEFAULT 1,
  telefono        text,
  note            text,
  stato           text NOT NULL DEFAULT 'in_attesa'::text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  id_ordine       uuid,
  id_prevendita   uuid,
  prezzo_totale   numeric DEFAULT 0.00,
  CONSTRAINT prenotazioni_pkey PRIMARY KEY (id)
);

CREATE TABLE public.prenotazioni_tavolo (
  id              uuid NOT NULL DEFAULT gen_random_uuid(),
  id_tavolo       uuid NOT NULL,
  id_evento       uuid,
  n_persone       integer,
  nome_cliente    text,
  stato           text,
  id_utente       uuid,
  id_drink        uuid,
  quantita_drink  integer DEFAULT 0,
  id_prenotazione uuid,
  quantita        integer DEFAULT 1,
  CONSTRAINT prenotazioni_tavolo_pkey PRIMARY KEY (id)
);

CREATE TABLE public.prenotazioni_prevendite (
  id              uuid NOT NULL DEFAULT gen_random_uuid(),
  id_prevendita   uuid NOT NULL,
  id_prenotazione uuid NOT NULL,
  id_utente       uuid,
  nome            text NOT NULL,
  cognome         text NOT NULL,
  data_nascita    date NOT NULL,
  CONSTRAINT prenotazioni_prevendite_pkey PRIMARY KEY (id)
);

-- ── Preferiti, notifiche, analytics ───────────────────────────────────────────

CREATE TABLE public.preferiti (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  id_utente  uuid NOT NULL,
  locale_id  uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT preferiti_pkey PRIMARY KEY (id),
  CONSTRAINT preferiti_user_id_locale_id_key UNIQUE (id_utente, locale_id)
);

CREATE TABLE public.notifiche (
  id         uuid NOT NULL DEFAULT gen_random_uuid(),
  utente_id  uuid NOT NULL,
  titolo     text NOT NULL,
  messaggio  text NOT NULL,
  tipo       text NOT NULL,
  related_id uuid,
  letto      boolean DEFAULT false,
  created_at timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notifiche_pkey PRIMARY KEY (id)
);

CREATE TABLE public.analytics_events (
  id          uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at  timestamptz DEFAULT now(),
  user_id     uuid,
  event_name  text NOT NULL,
  metadata    jsonb DEFAULT '{}'::jsonb,
  platform    text,
  app_version text,
  is_debug    boolean DEFAULT false,
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id)
);


-- =============================================================================
-- 3. FOREIGN KEY
-- =============================================================================

-- citta → provincia
ALTER TABLE public.citta
  ADD CONSTRAINT citta_id_provincia_fkey FOREIGN KEY (id_provincia)
  REFERENCES public.provincia(id_provincia) ON DELETE CASCADE;

-- cap → citta
ALTER TABLE public.cap
  ADD CONSTRAINT cap_id_citta_fkey FOREIGN KEY (id_citta)
  REFERENCES public.citta(id_citta) ON DELETE CASCADE;

-- posti_famosi → citta (NO ACTION)
ALTER TABLE public.posti_famosi
  ADD CONSTRAINT posti_famosi_id_citta_fkey FOREIGN KEY (id_citta)
  REFERENCES public.citta(id_citta);

-- utenti → auth.users
ALTER TABLE public.utenti
  ADD CONSTRAINT users_id_fkey FOREIGN KEY (id)
  REFERENCES auth.users(id) ON DELETE CASCADE;

-- utenti_numeri_telefono → utenti, paesi
ALTER TABLE public.utenti_numeri_telefono
  ADD CONSTRAINT utenti_numeri_telefono_id_utente_fkey FOREIGN KEY (id_utente)
  REFERENCES public.utenti(id) ON DELETE CASCADE;
ALTER TABLE public.utenti_numeri_telefono
  ADD CONSTRAINT user_phones_country_id_fkey FOREIGN KEY (country_id)
  REFERENCES public.paesi(id) ON DELETE CASCADE;

-- locali → citta
ALTER TABLE public.locali
  ADD CONSTRAINT locali_id_citta_fkey FOREIGN KEY (id_citta)
  REFERENCES public.citta(id_citta) ON DELETE SET NULL;

-- gestori → locali
ALTER TABLE public.gestori
  ADD CONSTRAINT gestori_club_id_fkey FOREIGN KEY (club_id)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- staff → locali
ALTER TABLE public.staff
  ADD CONSTRAINT staff_club_id_fkey FOREIGN KEY (club_id)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- ingressi_giornalieri → locali
ALTER TABLE public.ingressi_giornalieri
  ADD CONSTRAINT ingressi_giornalieri_club_id_fkey FOREIGN KEY (club_id)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- eventi → locali
ALTER TABLE public.eventi
  ADD CONSTRAINT eventi_club_id_fkey FOREIGN KEY (club_id)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- prevendite → eventi
ALTER TABLE public.prevendite
  ADD CONSTRAINT prevendita_id_evento_fkey FOREIGN KEY (id_evento)
  REFERENCES public.eventi(id) ON DELETE CASCADE;

-- tavoli → locali
ALTER TABLE public.tavoli
  ADD CONSTRAINT tavolo_id_locale_fkey FOREIGN KEY (id_locale)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- tavoli_eventi → tavoli, eventi (NO ACTION)
ALTER TABLE public.tavoli_eventi
  ADD CONSTRAINT tavoli_eventi_id_tavolo_fkey FOREIGN KEY (id_tavolo)
  REFERENCES public.tavoli(id_tavolo);
ALTER TABLE public.tavoli_eventi
  ADD CONSTRAINT tavoli_eventi_id_evento_fkey FOREIGN KEY (id_evento)
  REFERENCES public.eventi(id);

-- ordini → utenti
ALTER TABLE public.ordini
  ADD CONSTRAINT ordini_utente_id_fkey FOREIGN KEY (utente_id)
  REFERENCES public.utenti(id) ON DELETE SET NULL;

-- prenotazioni → eventi, utenti, ordini, prevendite
ALTER TABLE public.prenotazioni
  ADD CONSTRAINT prenotazioni_evento_id_fkey FOREIGN KEY (id_evento)
  REFERENCES public.eventi(id) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni
  ADD CONSTRAINT prenotazioni_id_utente_fkey FOREIGN KEY (id_utente)
  REFERENCES public.utenti(id) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni
  ADD CONSTRAINT prenotazioni_id_ordine_fkey FOREIGN KEY (id_ordine)
  REFERENCES public.ordini(id) ON DELETE SET NULL;
ALTER TABLE public.prenotazioni
  ADD CONSTRAINT prenotazioni_id_prevendita_fkey FOREIGN KEY (id_prevendita)
  REFERENCES public.prevendite(id_prevendita);

-- prenotazioni_tavolo → tavoli, eventi, utenti, drink, prenotazioni
ALTER TABLE public.prenotazioni_tavolo
  ADD CONSTRAINT prenotazioni_tavolo_id_tavolo_fkey FOREIGN KEY (id_tavolo)
  REFERENCES public.tavoli(id_tavolo) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni_tavolo
  ADD CONSTRAINT prenotazioni_tavolo_id_evento_fkey FOREIGN KEY (id_evento)
  REFERENCES public.eventi(id) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni_tavolo
  ADD CONSTRAINT prenotazioni_tavolo_id_utente_fkey FOREIGN KEY (id_utente)
  REFERENCES public.utenti(id) ON DELETE SET NULL;
ALTER TABLE public.prenotazioni_tavolo
  ADD CONSTRAINT prenotazioni_tavolo_id_drink_fkey FOREIGN KEY (id_drink)
  REFERENCES public.drink(id_drink) ON DELETE SET NULL;
ALTER TABLE public.prenotazioni_tavolo
  ADD CONSTRAINT prenotazioni_tavolo_id_prenotazione_fkey FOREIGN KEY (id_prenotazione)
  REFERENCES public.prenotazioni(id) ON DELETE CASCADE;

-- prenotazioni_prevendite → prevendite, prenotazioni, utenti
ALTER TABLE public.prenotazioni_prevendite
  ADD CONSTRAINT prenotazioni_prevendite_id_prevendita_fkey FOREIGN KEY (id_prevendita)
  REFERENCES public.prevendite(id_prevendita) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni_prevendite
  ADD CONSTRAINT prenotazioni_prevendite_id_prenotazione_fkey FOREIGN KEY (id_prenotazione)
  REFERENCES public.prenotazioni(id) ON DELETE CASCADE;
ALTER TABLE public.prenotazioni_prevendite
  ADD CONSTRAINT prenotazioni_prevendite_id_utente_fkey FOREIGN KEY (id_utente)
  REFERENCES public.utenti(id) ON DELETE SET NULL;

-- preferiti → utenti, locali
ALTER TABLE public.preferiti
  ADD CONSTRAINT preferiti_id_utente_fkey FOREIGN KEY (id_utente)
  REFERENCES public.utenti(id) ON DELETE CASCADE;
ALTER TABLE public.preferiti
  ADD CONSTRAINT preferiti_locale_id_fkey FOREIGN KEY (locale_id)
  REFERENCES public.locali(id) ON DELETE CASCADE;

-- notifiche → auth.users
ALTER TABLE public.notifiche
  ADD CONSTRAINT notifiche_utente_id_fkey FOREIGN KEY (utente_id)
  REFERENCES auth.users(id) ON DELETE CASCADE;

-- analytics_events → auth.users
ALTER TABLE public.analytics_events
  ADD CONSTRAINT analytics_events_user_id_fkey FOREIGN KEY (user_id)
  REFERENCES auth.users(id) ON DELETE SET NULL;


-- =============================================================================
-- 4. INDICI (esclusi quelli auto-creati da PK e UNIQUE constraint)
-- =============================================================================

-- analytics_events
CREATE INDEX idx_analytics_event_name ON public.analytics_events USING btree (event_name, created_at DESC);
CREATE INDEX idx_analytics_user       ON public.analytics_events USING btree (user_id);

-- citta
CREATE INDEX idx_citta_nome      ON public.citta USING btree (nome_citta text_pattern_ops);
CREATE INDEX idx_citta_nome_trgm ON public.citta USING gin (nome_citta gin_trgm_ops);
CREATE INDEX idx_citta_posizione ON public.citta USING gist (posizione);
CREATE UNIQUE INDEX idx_citta_unique ON public.citta USING btree (nome_citta, id_provincia);

-- eventi
CREATE INDEX idx_eventi_club_id     ON public.eventi USING btree (club_id);
CREATE INDEX idx_eventi_club_stato  ON public.eventi USING btree (club_id, stato, inizio_evento);
CREATE INDEX idx_eventi_date        ON public.eventi USING btree (inizio_evento);

-- gestori
CREATE INDEX gestori_club_idx        ON public.gestori USING btree (club_id);
CREATE INDEX idx_gestori_club_attivo ON public.gestori USING btree (club_id, attivo);

-- ingressi_giornalieri
CREATE INDEX ingressi_club_data_idx ON public.ingressi_giornalieri USING btree (club_id, data);

-- locali
CREATE INDEX idx_locali_citta     ON public.locali USING btree (id_citta);
CREATE INDEX idx_locali_posizione ON public.locali USING gist (posizione);

-- notifiche
CREATE INDEX idx_notifiche_utente_letto ON public.notifiche USING btree (utente_id, letto, created_at DESC);

-- ordini
CREATE INDEX idx_ordini_stato     ON public.ordini USING btree (stato);
CREATE INDEX idx_ordini_stripe_pi ON public.ordini USING btree (stripe_payment_intent_id);
CREATE INDEX idx_ordini_utente    ON public.ordini USING btree (utente_id);
CREATE INDEX idx_ordini_utente_id ON public.ordini USING btree (utente_id);  -- NB: duplica idx_ordini_utente nel DB sorgente

-- preferiti
CREATE INDEX idx_preferiti_utente ON public.preferiti USING btree (id_utente, locale_id);

-- prenotazioni
CREATE INDEX idx_prenotazioni_evento_stato ON public.prenotazioni USING btree (id_evento, stato);
CREATE INDEX idx_prenotazioni_utente       ON public.prenotazioni USING btree (id_utente);

-- prenotazioni_prevendite
CREATE INDEX idx_prenot_prev_prenotazione ON public.prenotazioni_prevendite USING btree (id_prenotazione);
CREATE INDEX idx_prenot_prev_utente       ON public.prenotazioni_prevendite USING btree (id_utente);

-- prenotazioni_tavolo
CREATE INDEX idx_prenot_tavolo_evento ON public.prenotazioni_tavolo USING btree (id_evento);
CREATE INDEX idx_prenot_tavolo_utente ON public.prenotazioni_tavolo USING btree (id_utente);
-- Indice unico parziale: blocca doppie prenotazioni dello stesso tavolo per lo stesso evento
-- escludendo quelle annullate.
CREATE UNIQUE INDEX uq_prenotazioni_tavolo_attiva
  ON public.prenotazioni_tavolo USING btree (id_tavolo, id_evento)
  WHERE ((stato IS NULL) OR (stato <> 'annullata'::text));

-- prevendite
CREATE INDEX idx_prevendite_evento ON public.prevendite USING btree (id_evento);

-- staff
CREATE INDEX staff_club_idx ON public.staff USING btree (club_id);

-- tavoli
CREATE INDEX idx_tavoli_locale ON public.tavoli USING btree (id_locale);

-- tavoli_eventi
CREATE INDEX idx_tavoli_eventi_evento ON public.tavoli_eventi USING btree (id_evento);
CREATE INDEX idx_tavoli_eventi_stato  ON public.tavoli_eventi USING btree (stato);
CREATE INDEX idx_tavoli_eventi_tavolo ON public.tavoli_eventi USING btree (id_tavolo);

-- utenti_numeri_telefono (duplicato presente nel DB sorgente: due indici UNIQUE
-- identici su (id_utente, telefono). Replicato per fedeltà; valutare se ridurre
-- a uno solo in fase di cleanup.)
CREATE UNIQUE INDEX users_phones_user_id_phone_uq ON public.utenti_numeri_telefono USING btree (id_utente, telefono);
CREATE UNIQUE INDEX users_phones_user_id_tel_uq   ON public.utenti_numeri_telefono USING btree (id_utente, telefono);


-- =============================================================================
-- 5. FUNZIONI (definite prima di trigger e policy che le usano)
-- =============================================================================

-- ── my_club_id: usata dalle policy RLS del gestionale ─────────────────────────
CREATE OR REPLACE FUNCTION public.my_club_id()
RETURNS uuid
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT club_id
  FROM public.gestori
  WHERE id = auth.uid()
    AND attivo = true
  LIMIT 1;
$function$;

-- ── set_updated_at: trigger generico (non usato attualmente, mantenuto) ───────
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- ── update_ordini_updated_at: trigger su ordini (non usato — vedi trg ordini) ─
CREATE OR REPLACE FUNCTION public.update_ordini_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

-- ── fn_decrement_prevendita_stock: BEFORE INSERT su prenotazioni_prevendite ──
CREATE OR REPLACE FUNCTION public.fn_decrement_prevendita_stock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_remaining integer;
BEGIN
  -- Decremento atomico con lock implicito su UPDATE
  UPDATE public.prevendite
  SET quantita_disponibile = quantita_disponibile - 1
  WHERE id_prevendita = NEW.id_prevendita
    AND quantita_disponibile > 0
  RETURNING quantita_disponibile INTO v_remaining;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Prevendita esaurita (id=%)', NEW.id_prevendita
      USING ERRCODE = 'P0001';
  END IF;

  RETURN NEW;
END;
$function$;

-- ── fn_restore_prevendita_stock: AFTER UPDATE su prenotazioni quando annullata ─
CREATE OR REPLACE FUNCTION public.fn_restore_prevendita_stock()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
BEGIN
  -- Specchia il decremento: 1 unità di stock per ogni riga in
  -- prenotazioni_prevendite collegata a questa prenotazione.
  UPDATE public.prevendite pv
  SET quantita_disponibile = pv.quantita_disponibile + sub.cnt
  FROM (
    SELECT id_prevendita, COUNT(*) AS cnt
    FROM public.prenotazioni_prevendite
    WHERE id_prenotazione = NEW.id
    GROUP BY id_prevendita
  ) sub
  WHERE pv.id_prevendita = sub.id_prevendita;

  RETURN NEW;
END;
$function$;

-- ── fn_update_posti_prenotati: AFTER INSERT/UPDATE/DELETE su prenotazioni ─────
CREATE OR REPLACE FUNCTION public.fn_update_posti_prenotati()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_evento_id uuid;
  v_count     integer;
BEGIN
  v_evento_id := COALESCE(NEW.id_evento, OLD.id_evento);

  SELECT COALESCE(SUM(n_persone), 0)
  INTO v_count
  FROM public.prenotazioni
  WHERE id_evento = v_evento_id
    AND stato = 'confermata';

  UPDATE public.eventi
  SET posti_prenotati = v_count,
      updated_at      = now()
  WHERE id = v_evento_id;

  RETURN COALESCE(NEW, OLD);
END;
$function$;

-- ── get_tavoli_disponibilita: rpc usata dall'app per la mappa tavoli ──────────
CREATE OR REPLACE FUNCTION public.get_tavoli_disponibilita(p_id_evento uuid)
RETURNS TABLE(id_tavolo uuid, occupato boolean)
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT t.id_tavolo,
         EXISTS (
           SELECT 1
           FROM public.prenotazioni_tavolo pt
           WHERE pt.id_tavolo = t.id_tavolo
             AND pt.id_evento = p_id_evento
             AND (pt.stato IS NULL OR pt.stato <> 'annullata')
         ) AS occupato
  FROM public.tavoli t
  WHERE t.id_locale = (
    SELECT e.club_id FROM public.eventi e WHERE e.id = p_id_evento
  );
$function$;

-- ── nearby_clubs: ricerca locali entro raggio_km dato (lat/lng utente) ────────
CREATE OR REPLACE FUNCTION public.nearby_clubs(
  user_lat   double precision,
  user_lng   double precision,
  raggio_km  double precision DEFAULT 50
)
RETURNS TABLE(
  id uuid,
  nome text,
  indirizzo text,
  citta text,
  id_citta uuid,
  logo_url text,
  foto_url text,
  famosita integer,
  generi_musicali text[],
  prezzo_indicativo smallint,
  descrizione text,
  link_tripadvisor text,
  lat double precision,
  lng double precision,
  distanza_km double precision
)
LANGUAGE sql
STABLE
AS $function$
  SELECT
    l.id,
    l.nome,
    l.indirizzo,
    c.nome_citta                    AS citta,
    l.id_citta,
    l.logo_url,
    l.foto_url,
    l.famosita,
    l.generi_musicali,
    l.prezzo_indicativo,
    l.descrizione,
    l.link_tripadvisor,
    COALESCE(l.lat, c.lat)          AS lat,
    COALESCE(l.lng, c.lng)          AS lng,
    ROUND(
      ST_Distance(
        ST_MakePoint(COALESCE(l.lng, c.lng), COALESCE(l.lat, c.lat))::geography,
        ST_MakePoint(user_lng, user_lat)::geography
      )::numeric / 1000,
      2
    )::FLOAT                        AS distanza_km
  FROM public.locali l
  LEFT JOIN public.citta c ON c.id_citta = l.id_citta
  WHERE
    COALESCE(l.lat, c.lat) IS NOT NULL
    AND COALESCE(l.lng, c.lng) IS NOT NULL
    AND ST_DWithin(
      ST_MakePoint(COALESCE(l.lng, c.lng), COALESCE(l.lat, c.lat))::geography,
      ST_MakePoint(user_lng, user_lat)::geography,
      raggio_km * 1000
    )
  ORDER BY distanza_km ASC;
$function$;

-- ── register_user_transaction: signup atomico utente + telefono ───────────────
CREATE OR REPLACE FUNCTION public.register_user_transaction(
  p_id_utente   uuid,
  p_nome        text,
  p_cognome     text,
  p_email       text,
  p_data_nascita date,
  p_telefono    text,
  p_country_iso text
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_is_adult   boolean := false;
  v_country_id uuid    := null;
  v_now        timestamptz := now();
  v_dial       text    := null;
  v_e164       text    := null;
BEGIN
  -- Hardening: solo l'utente loggato può registrare il proprio profilo
  IF auth.uid() IS NULL OR auth.uid() <> p_id_utente THEN
    RAISE EXCEPTION 'Forbidden: caller is not the target user'
      USING ERRCODE = '42501';
  END IF;

  IF p_nome IS NULL OR length(trim(p_nome)) = 0 THEN
    RAISE EXCEPTION 'Nome obbligatorio';
  END IF;
  IF p_cognome IS NULL OR length(trim(p_cognome)) = 0 THEN
    RAISE EXCEPTION 'Cognome obbligatorio';
  END IF;
  IF p_data_nascita IS NULL THEN
    RAISE EXCEPTION 'Data di nascita obbligatoria';
  END IF;
  IF p_telefono IS NULL OR length(trim(p_telefono)) < 7 THEN
    RAISE EXCEPTION 'Telefono non valido';
  END IF;

  v_is_adult := (date_part('year', age(current_date, p_data_nascita)) >= 18);

  SELECT id, numero_prefisso
  INTO v_country_id, v_dial
  FROM public.paesi
  WHERE upper(iso_code) = upper(p_country_iso)
  LIMIT 1;

  v_e164 := replace(coalesce(p_telefono, ''), ' ', '');
  IF v_e164 IS NULL OR v_e164 = '' THEN
    RAISE EXCEPTION 'Telefono non valido';
  END IF;
  IF v_e164 !~ '^\+' THEN
    v_e164 := '+' || v_e164;
  END IF;

  INSERT INTO public.utenti
    (id, nome, cognome, email, data_nascita, maggiorenne, created_at)
  VALUES
    (p_id_utente, p_nome, p_cognome, p_email, p_data_nascita, v_is_adult, v_now)
  ON CONFLICT (id) DO UPDATE
    SET nome         = EXCLUDED.nome,
        cognome      = EXCLUDED.cognome,
        email        = EXCLUDED.email,
        data_nascita = EXCLUDED.data_nascita,
        maggiorenne  = EXCLUDED.maggiorenne,
        updated_at   = v_now;

  INSERT INTO public.utenti_numeri_telefono
    (id_utente, country_id, telefono, is_primary, is_verified, created_at)
  VALUES
    (p_id_utente, v_country_id, v_e164, true, false, v_now)
  ON CONFLICT (id_utente, telefono) DO UPDATE
    SET country_id  = EXCLUDED.country_id,
        is_primary  = EXCLUDED.is_primary,
        is_verified = EXCLUDED.is_verified,
        updated_at  = v_now;

  RETURN json_build_object(
    'user_id',     p_id_utente,
    'country_id',  v_country_id,
    'maggiorenne', v_is_adult,
    'status',      'ok'
  );
END;
$function$;

-- ── get_gestore_by_codice: ATTENZIONE — vedi nota a fine file ─────────────────
-- BUG NEL DB SORGENTE: referenzia `public.clubs` che NON esiste (la tabella è
-- `public.locali`). La function viene ricreata identica per fedeltà, ma deve
-- essere fixata prima di essere chiamata in produzione.
CREATE OR REPLACE FUNCTION public.get_gestore_by_codice(p_codice text)
RETURNS TABLE(email text, club_nome text)
LANGUAGE plpgsql
STABLE SECURITY DEFINER
AS $function$
begin
  return query
    select g.email, c.nome
    from public.gestori g
    join public.clubs c on c.id = g.club_id
    where g.codice = p_codice
      and g.attivo = true
    limit 1;
end;
$function$;


-- =============================================================================
-- 6. TRIGGER
-- =============================================================================

-- updated_at automatico via moddatetime
CREATE TRIGGER trg_eventi_updated_at
  BEFORE UPDATE ON public.eventi
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER trg_ordini_updated_at
  BEFORE UPDATE ON public.ordini
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER trg_prenotazioni_updated_at
  BEFORE UPDATE ON public.prenotazioni
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

CREATE TRIGGER trg_utenti_updated_at
  BEFORE UPDATE ON public.utenti
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');

-- Logica di business sulle prenotazioni
CREATE TRIGGER trg_update_posti_prenotati
  AFTER INSERT OR DELETE OR UPDATE ON public.prenotazioni
  FOR EACH ROW EXECUTE FUNCTION public.fn_update_posti_prenotati();

CREATE TRIGGER trg_restore_prevendita_stock
  AFTER UPDATE OF stato ON public.prenotazioni
  FOR EACH ROW
  WHEN (new.stato = 'annullata'::text
        AND (old.stato IS NULL OR old.stato <> 'annullata'::text))
  EXECUTE FUNCTION public.fn_restore_prevendita_stock();

CREATE TRIGGER trg_decrement_prevendita_stock
  BEFORE INSERT ON public.prenotazioni_prevendite
  FOR EACH ROW EXECUTE FUNCTION public.fn_decrement_prevendita_stock();


-- =============================================================================
-- 7. ENABLE RLS su tutte le tabelle public
-- =============================================================================

ALTER TABLE public.analytics_events        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cap                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.citta                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drink                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventi                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gestori                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingressi_giornalieri    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locali                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifiche               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordini                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paesi                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posti_famosi            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preferiti               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prenotazioni            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prenotazioni_prevendite ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prenotazioni_tavolo     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prevendite              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provincia               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tavoli                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tavoli_eventi           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.utenti                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.utenti_numeri_telefono  ENABLE ROW LEVEL SECURITY;


-- =============================================================================
-- 8. POLICY RLS
-- =============================================================================

-- ── analytics_events ─────────────────────────────────────────────────────────
CREATE POLICY "Allow authenticated inserts" ON public.analytics_events
  FOR INSERT TO public
  WITH CHECK ((user_id = auth.uid()) OR (user_id IS NULL));

-- ── cap ───────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono cap" ON public.cap
  FOR SELECT TO public USING (true);

-- ── citta ─────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono citta" ON public.citta
  FOR SELECT TO public USING (true);

-- ── drink ─────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono drink" ON public.drink
  FOR SELECT TO public USING (true);

-- ── eventi ────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono eventi" ON public.eventi
  FOR SELECT TO public USING (true);

CREATE POLICY gestori_all_eventi ON public.eventi
  FOR ALL TO authenticated
  USING (club_id = my_club_id())
  WITH CHECK (club_id = my_club_id());

-- ── gestori ───────────────────────────────────────────────────────────────────
CREATE POLICY gestori_select ON public.gestori
  FOR SELECT TO authenticated
  USING (club_id = my_club_id());

-- ── ingressi_giornalieri ──────────────────────────────────────────────────────
CREATE POLICY gestori_all_ingressi ON public.ingressi_giornalieri
  FOR ALL TO authenticated
  USING (club_id = my_club_id())
  WITH CHECK (club_id = my_club_id());

-- ── locali ────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono locali" ON public.locali
  FOR SELECT TO public USING (true);

CREATE POLICY gestori_select_club ON public.locali
  FOR SELECT TO authenticated
  USING (id = my_club_id());

CREATE POLICY gestori_update_club ON public.locali
  FOR UPDATE TO authenticated
  USING (id = my_club_id())
  WITH CHECK (id = my_club_id());

-- ── notifiche ─────────────────────────────────────────────────────────────────
CREATE POLICY "Gli utenti possono vedere le proprie notifiche" ON public.notifiche
  FOR SELECT TO public USING (auth.uid() = utente_id);

CREATE POLICY "Gli utenti possono aggiornare le proprie notifiche" ON public.notifiche
  FOR UPDATE TO public USING (auth.uid() = utente_id);

CREATE POLICY "Gli utenti possono inserire le proprie notifiche" ON public.notifiche
  FOR INSERT TO public
  WITH CHECK (utente_id = auth.uid());

-- ── ordini ────────────────────────────────────────────────────────────────────
CREATE POLICY "Utente legge propri ordini" ON public.ordini
  FOR SELECT TO authenticated
  USING (utente_id = auth.uid());

CREATE POLICY "Utente inserisce propri ordini" ON public.ordini
  FOR INSERT TO public
  WITH CHECK (utente_id = auth.uid());

CREATE POLICY "Utente aggiorna propri ordini" ON public.ordini
  FOR UPDATE TO public
  USING (auth.uid() = utente_id)
  WITH CHECK (auth.uid() = utente_id);

-- ── paesi ─────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono paesi" ON public.paesi
  FOR SELECT TO public USING (true);

-- ── posti_famosi ──────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono posti famosi" ON public.posti_famosi
  FOR SELECT TO public USING (true);

-- ── preferiti ─────────────────────────────────────────────────────────────────
CREATE POLICY "Utente gestisce suoi preferiti" ON public.preferiti
  FOR ALL TO authenticated
  USING (id_utente = auth.uid())
  WITH CHECK (id_utente = auth.uid());

-- ── prenotazioni ──────────────────────────────────────────────────────────────
CREATE POLICY "Gli utenti possono vedere le proprie prenotazioni" ON public.prenotazioni
  FOR SELECT TO public USING (auth.uid() = id_utente);

CREATE POLICY "Gli utenti possono inserire le proprie prenotazioni" ON public.prenotazioni
  FOR INSERT TO public
  WITH CHECK (id_utente = auth.uid());

-- ── prenotazioni_prevendite ───────────────────────────────────────────────────
CREATE POLICY "Gli utenti possono vedere i dettagli delle proprie prevendite" ON public.prenotazioni_prevendite
  FOR SELECT TO public USING (auth.uid() = id_utente);

CREATE POLICY "Gli utenti possono inserire i dettagli delle proprie prevendite" ON public.prenotazioni_prevendite
  FOR INSERT TO public
  WITH CHECK (id_utente = auth.uid());

-- ── prenotazioni_tavolo ───────────────────────────────────────────────────────
CREATE POLICY "Gli utenti possono vedere le proprie prenotazioni tavolo" ON public.prenotazioni_tavolo
  FOR SELECT TO public USING (auth.uid() = id_utente);

CREATE POLICY "Gli utenti possono inserire le proprie prenotazioni tavolo" ON public.prenotazioni_tavolo
  FOR INSERT TO public
  WITH CHECK (id_utente = auth.uid());

-- ── prevendite ────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono prevendite" ON public.prevendite
  FOR SELECT TO public USING (true);

-- ── provincia ─────────────────────────────────────────────────────────────────
CREATE POLICY provincia_read_public ON public.provincia
  FOR SELECT TO public USING (true);

-- ── staff ─────────────────────────────────────────────────────────────────────
CREATE POLICY gestori_all_staff ON public.staff
  FOR ALL TO authenticated
  USING (club_id = my_club_id())
  WITH CHECK (club_id = my_club_id());

-- ── tavoli ────────────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono tavoli" ON public.tavoli
  FOR SELECT TO public USING (true);

-- ── tavoli_eventi ─────────────────────────────────────────────────────────────
CREATE POLICY "Tutti leggono disponibilità tavoli" ON public.tavoli_eventi
  FOR SELECT TO public USING (true);

CREATE POLICY gestori_all_tavoli_eventi ON public.tavoli_eventi
  FOR ALL TO authenticated
  USING (id_evento IN (SELECT eventi.id FROM eventi WHERE (eventi.club_id = my_club_id())))
  WITH CHECK (id_evento IN (SELECT eventi.id FROM eventi WHERE (eventi.club_id = my_club_id())));

-- ── utenti ────────────────────────────────────────────────────────────────────
CREATE POLICY "Gli utenti gestiscono proprio profilo" ON public.utenti
  FOR ALL TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- ── utenti_numeri_telefono ────────────────────────────────────────────────────
CREATE POLICY "Gestione del proprio telefono" ON public.utenti_numeri_telefono
  FOR ALL TO authenticated
  USING (id_utente = auth.uid())
  WITH CHECK (id_utente = auth.uid());


-- =============================================================================
-- 9. VIEW
-- =============================================================================

CREATE OR REPLACE VIEW public.v_analytics_details AS
  SELECT id,
    created_at,
    event_name,
    platform,
    app_version,
    user_id,
    is_debug,
    metadata ->> 'page_name'::text AS page_name,
    (metadata ->> 'duration_seconds'::text)::numeric AS duration_seconds,
    metadata ->> 'club_id'::text AS club_id,
    metadata ->> 'club_name'::text AS club_name,
    metadata ->> 'type'::text AS funnel_type,
    metadata ->> 'amount'::text AS amount,
    metadata ->> 'method'::text AS auth_method,
    metadata ->> 'error'::text AS error_message
  FROM analytics_events;

CREATE OR REPLACE VIEW public.v_eventi_dashboard AS
  SELECT e.id AS evento_id,
    e.nome AS evento_nome,
    e.inizio_evento,
    e.fine_evento,
    e.stato,
    e.ingressi_previsti,
    e.posti_prenotati,
    e.prezzo_ingresso,
    e.incasso_previsto,
    l.id AS club_id,
    l.nome AS club_nome,
    c.nome_citta,
    (SELECT count(*) FROM prenotazioni pr
      WHERE pr.id_evento = e.id AND pr.stato = 'confermata'::text) AS prenotazioni_confermate,
    (SELECT COALESCE(sum(pr.prezzo_totale), 0::numeric) FROM prenotazioni pr
      WHERE pr.id_evento = e.id AND pr.stato = 'confermata'::text) AS incasso_reale,
    (SELECT count(*) FROM prenotazioni_prevendite pp
        JOIN prevendite pv ON pv.id_prevendita = pp.id_prevendita
      WHERE pv.id_evento = e.id) AS biglietti_venduti,
    (SELECT count(*) FROM prenotazioni_tavolo pt
      WHERE pt.id_evento = e.id AND pt.stato <> 'annullata'::text) AS tavoli_prenotati
  FROM eventi e
    JOIN locali l ON l.id = e.club_id
    LEFT JOIN citta c ON c.id_citta = l.id_citta
  ORDER BY e.inizio_evento DESC;

CREATE OR REPLACE VIEW public.v_utenti_profilo AS
  SELECT u.id,
    u.email,
    u.nome,
    u.cognome,
    u.data_nascita,
    date_part('year'::text,
      age(CURRENT_DATE::timestamp with time zone,
          u.data_nascita::timestamp with time zone)) >= 18::double precision AS maggiorenne,
    u.raggio_km,
    u.created_at,
    u.updated_at,
    p.telefono,
    p.is_verified,
    pa.iso_code AS country_iso,
    pa.nome AS country_nome
  FROM utenti u
    LEFT JOIN utenti_numeri_telefono p ON p.id_utente = u.id AND p.is_primary = true
    LEFT JOIN paesi pa ON pa.id = p.country_id;


-- =============================================================================
-- FINE — Note importanti
-- =============================================================================
--
-- ⚠️  BUG NEL DB SORGENTE (non risolto per fedeltà di replica):
--
--   La function `public.get_gestore_by_codice` referenzia `public.clubs` che
--   NON esiste (la tabella si chiama `public.locali`). Eseguendo la function
--   sul DB di produzione si otterrà: ERROR: relation "public.clubs" does not
--   exist. Fix da applicare in una migrazione successiva:
--
--     CREATE OR REPLACE FUNCTION public.get_gestore_by_codice(p_codice text)
--     RETURNS TABLE(email text, club_nome text)
--     LANGUAGE plpgsql STABLE SECURITY DEFINER
--     AS $function$
--     begin
--       return query
--         select g.email, l.nome
--         from public.gestori g
--         join public.locali l on l.id = g.club_id
--         where g.codice = p_codice and g.attivo = true
--         limit 1;
--     end;
--     $function$;
--
-- ⚠️  Indici duplicati nel DB sorgente (replicati per fedeltà):
--   • `idx_ordini_utente` + `idx_ordini_utente_id` — entrambi su ordini.utente_id
--   • `users_phones_user_id_phone_uq` + `users_phones_user_id_tel_uq` —
--     entrambi UNIQUE su (id_utente, telefono)
--   Valutare se eliminare i duplicati in una migrazione di cleanup.
--
-- ℹ️  Funzione `set_updated_at()` e `update_ordini_updated_at()` sono presenti
--   nel DB sorgente ma NON sono associate a nessun trigger (i trigger
--   updated_at usano tutti `extensions.moddatetime`). Mantenute per
--   fedeltà; potrebbero essere rimosse se non più necessarie.
-- =============================================================================
